language: android

jdk: oraclejdk8

env:
  global:
    - ANDROID_TARGET=android-24
    - ANDROID_ABI=armeabi-v7a
  matrix:
    - TERM=dumb

android:
  components:
  - tools
  - platform-tools
  - build-tools-24.0.2
  - android-24
  - extra-android-m2repository
  - extra-google-m2repository
  - sys-img-${ANDROID_ABI}-${ANDROID_TARGET}


before_script:
#  - echo no | android create avd --force --name test --target $ANDROID_TARGET --abi $ANDROID_ABI
#  - emulator -avd test -no-skin -no-audio -no-window &

script:
  - ./gradlew build jacocoTestReport assembleAndroidTest
  - echo no | android create avd --force -n test -t $ANDROID_TARGET --abi $ANDROID_ABI
  - emulator -avd test -no-skin -no-audio -no-window &
  - android-wait-for-emulator
  - adb shell setprop dalvik.vm.dexopt-flags v=n,o=v
  - ./gradlew connectedCheck

before_install:
  - chmod +x gradlew

after_success:
  - bash <(curl -s https://codecov.io/bash)

after_failure:
  - ./gradlew clean check --debug
